### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/block-jetpack#1]
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function 'my_plugin_menu_remover' not found or invalid function name in /var/www/commons.hwdsb.on.ca/wordpress/wp-includes/plugin.php on line 496

**Comment by r-a-y** [comment]
To fix this, since the my_plugin_menu_remover() function is not in use, comment out line 15:
https://github.com/hwdsbcommons/block-jetpack/blob/master/jetpack_block.php#L15

**Comment by mrjarbenne** [comment]
Right. Thanks for that. I had commented out the rest to gain back access to the menu.
